-- Oneday_Project_iolist

DROP TABLE tbl_iolist;

CREATE TABLE tbl_iolist(
    IO_SEQ  	NUMBER	PRIMARY KEY,
    IO_DATE	    VARCHAR2(10),
    IO_TIME	    VARCHAR2(10),
    IO_PNAME	nVARCHAR2(30),	
    IO_INOUT	CHAR(1),
    IO_PRICE	NUMBER,
    IO_QUAN	    NUMBER,
    IO_TOTAL	NUMBER		
);

DROP SEQUENCE seq_iolist;

CREATE SEQUENCE seq_iolist
START WITH 1 INCREMENT BY 1;

INSERT INTO tbl_iolist(IO_SEQ, IO_PNAME, IO_INOUT, IO_PRICE) VALUES(SEQ_IOLIST.NEXTVAL, '후드티', 'I', 12000);
INSERT INTO tbl_iolist(IO_SEQ, IO_PNAME, IO_INOUT, IO_PRICE) VALUES(SEQ_IOLIST.NEXTVAL, '가디건', 'I', 39000);


SELECT * FROM tbl_iolist;

COMMIT;